### ISSUE TITLE
[Bug]: /wp-content/languages/plugins/" directory does not exist (CI)

### ISSUE THREAD

**Issue by benoitchantre** [inpsyde/wp-translation-downloader#29]
### Description of the bug

I have updated this depency from version 2.04 to version 2.1.

I have now an issue in my Github workflow : `/wp-content/languages/plugins/" directory does not exist`

The `auto-run` parameter is set to `false`.
Translations are downloaded with the following command: `composer wp-translation-downloader:download`

### Reproduction instructions

- Set `auto-run` to `false`
- Run `composer install` and `composer wp-translation-downloader:download` in a Github workflow

### Expected behavior

There should be not issue :-)

### Environment info

Github workflow (CI)

Main build steps:
- install dev dependencies
- run some tests (phpcs)
- remove dev dependencies
- download languages
- ...

### Relevant log output

```shell
composer install --no-dev --classmap-authoritative --no-interaction --no-ansi --no-progress
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Package operations: 0 installs, 0 updates, 5 removals
  - Removing wpackagist-plugin/query-monitor (3.9.0)
  - Removing wp-coding-standards/wpcs (2.3.0)
  - Removing phpcompatibility/phpcompatibility-wp (2.1.3)
  - Removing phpcompatibility/phpcompatibility-paragonie (1.3.1)
  - Removing phpcompatibility/php-compatibility (9.3.5)
Deleting public/wp-content/plugins/query-monitor/ - deleted

                            
            Inpsyde         
                            
    WP Translation Downloader

Error: The "/home/runner/work/myproject/myproject/public/wp-content/languages/plugins/" directory does not exist.

In Finder.php line 592:
                                                                               
  The "/home/runner/work/myproject/myproject/public  
  /wp-content/languages/plugins/" directory does not exist.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Chrico** [comment]
Hey ☕ 
thanks for reporting. Can you maybe see more when you run with `-vvv` and provide some example composer.json / wp-translation-downloader.json so that i can try to reproduce it? :)

**Comment by Chrico** [comment]
@benoitchantre did some small improvements when iterating over `TranslatablePackage` to ensure that those `languageDirectory()` exist before download & unzip the files. Additionally i improved the `trim()` of trailing slashes for directory input via `wp-translation-downloader`-configuration. Could you quickly test with `dev-master` ? :) 

See changes in: https://github.com/inpsyde/wp-translation-downloader/commit/098c71316e07c1f27876814b4dd57ec1b6cbf03a

**Comment by benoitchantre** [comment]
@Chrico I did a quick test and it didn't worked.

Here's a simplified version of my `composer.json`

```json
{
  "license": "MIT",
  "type": "project",
  "repositories": [
    {
      "type": "composer",
      "url": "https://wpackagist.org"
    }
  ],
  "require": {
    "php": ">=7.2.5",
    "composer/installers": "^1.3",
    "inpsyde/wp-translation-downloader": "dev-master",
    "johnpbloch/wordpress": "5.9.*",
  },
  "require-dev": {
    "dealerdirect/phpcodesniffer-composer-installer": "^0.7",
    "phpcompatibility/phpcompatibility-wp": "^2.1",
    "roave/security-advisories": "dev-master",
    "squizlabs/php_codesniffer": "^3.4",
    "wp-coding-standards/wpcs": "^2.3",
  },
  "config": {
    "allow-plugins": {
      "dealerdirect/phpcodesniffer-composer-installer": true,
      "composer/installers": true,
      "johnpbloch/wordpress-core-installer": true,
      "inpsyde/wp-translation-downloader": true
    },
    "vendor-dir": "vendor",
    "preferred-install": "dist",
    "optimize-autoloader": true,
    "sort-packages": true
  },
  "extra": {
    "installer-paths": {
      "public/wp-content/mu-plugins/{$name}": [
        "wearerequired/wp-cli-clear-opcache",
        "type:wordpress-muplugin"
      ],
      "public/wp-content/plugins/{$name}/": [
        "type:wordpress-plugin"
      ],
      "public/wp-content/themes/{$name}/": [
        "type:wordpress-theme"
      ]
    },
    "wordpress-install-dir": "public/wp",
    "wp-translation-downloader": {
      "auto-run": false,
      "api": {
        "names": {
          "gravity/gravityforms": "https://packages.translationspress.com/rocketgenius/gravityforms/packages.json"
        }
      },
      "directory": "public/wp-content/languages",
      "languages": [
        "de_DE",
        "en_GB",
        "it_IT",
        "fr_FR"
      ]
    }
  }
}

```

And a simplified version of my deployment workflow (only the build part with unrelated steps removed)

```yaml
name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        options:
          - test
          - staging
          - production
        default: 'test'

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    concurrency:
      group: deploy-${{ github.event.inputs.environment }}
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Setup PHP
        uses: shivammathur/setup-php@448bd61c6fe9db2113173467e4c22b87ddc2971a
        with:
          php-version: '7.4'
          coverage: none
          tools: wp-cli

      - name: Validate composer.json and composer.lock
        run: composer validate --no-check-publish --strict

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Configure Composer cache
        uses: actions/cache@48af2dc4a9e8278b89d7fa154b955c30c6aaab09
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
            ${{ runner.os }}-composer-

      - name: Run make install with dev dependencies
        run: make install WP_ENVIRONMENT_TYPE=local

      - name: Check coding standards
        run: make check-phpcs

      - name: Remove dev dependencies
        run: touch composer.lock && make install WP_ENVIRONMENT_TYPE=production

      - name: Download translations files
        run: composer wp-translation-downloader:download
```

`make install WP_ENVIRONMENT_TYPE=local` runs `composer install --no-interaction --no-ansi --no-progress` and copy required some files that are not related to PHP if needed.

`make install WP_ENVIRONMENT_TYPE=production` runs `composer install --no-dev --classmap-authoritative --no-interaction --no-ansi --no-progress` and copy required some files that are not related to PHP if needed.
